#!/usr/bin/env python

import time
import tractor as tr
import tractor.types_double as tt
import numpy as np
import matplotlib.pyplot as plt

print "hello"

noise = 0.1
stdev = 0.1
activation = "tanh"
units = 256
weight_regularization = 0.01
activity_regularization = 0.01
bias_regularization = 0.01
layers = 3

#tr.logger.verbosity = 3
tr.profiler.start()

input = tt.InputLayer()
output = input
for i in range(layers):
    output = tt.DenseLayer(
        units,
        activation=activation,
        stdev=stdev,
        weight_regularization=weight_regularization,
        activity_regularization=activity_regularization,
        bias_regularization=bias_regularization,
    )(output)
output = tt.DenseLayer(1)(output)

print "hello"

network = tt.NeuralNetwork([input], [output])

xx = np.linspace(-5, 5, 100)

def r(x):
    #return x
    return tr.add_random_normal(x, tt.Tensor([tt.Scalar(noise)]))

def g(x):
    return network.predict(r(x))

def f():
    print "f begin"
    for xf in xx:
        x = tt.Tensor([xf])
        y = g(x)
        tr.goal(y - tr.sin(x))
    print "f ready"

print "rec begin"
prog = tr.record(f)
print "rec ready"
print prog

def test():
    plt.clf()
    #plt.plot(xx, np.sin(xx))
    plt.plot(xx, [np.sin(r(tt.Tensor([x])).value[0]) for x in xx])
    #plt.plot(xx, [g(tt.Tensor([x])).value[0] for x in xx])
    plt.plot(xx, [network.predict(tt.Tensor([x])).value[0] for x in xx])
    key = plt.waitforbuttonpress(timeout=0.001)
    if key is True:
        exit(0)

solver = tt.LeastSquaresSolver(tr.DefaultEngine())
solver.regularization = 1
solver.max_linear_iterations = 10
solver.step_scaling = 1

# solver = tt.GradientDescentSolver(tr.DefaultEngine())
# solver.learning_rate = 0.0001

solver.compile(prog)

solver.timeout = 0.01
while True:
    #print tr.logger.verbosity
    solver.solve()
    test()
