#!/usr/bin/env python

import time
import tractor as tr

print tr

print tr.DefaultEngine()

import tractor.types_double as tt

a = tt.Scalar(3)
b = tt.Scalar(2)

def f():
    global x
    tr.input(a)
    tr.input(b)
    x = tr.mul(a, b)
    x = tr.add(x, tt.Scalar(0.1))
    tr.output(x)

prog = tr.record(f)

print prog.constants
print prog.inputs
print prog.instructions
print prog.outputs

engine = tr.DefaultEngine()
memory = engine.createMemory()
executable = engine.compile(prog)

print x.value

a.value = 2
b.value = 7
executable.run(memory)

print x.value
