#!/usr/bin/env python

import time
import tractor as tr
import tractor.types_double as tt

a = tt.Scalar(3)
print "a", a

def f():
    global x, b
    b = tt.Scalar(2)
    tt.variable(a)
    tt.variable(b)
    x = tr.mul(a, b) + tt.Scalar(0.3)
    x += tt.Scalar(0.2)
    tt.output(x)

print "a"

prog = tr.record(f)

print "b"

print prog.constants
print prog.inputs
print prog.instructions
print prog.outputs

engine = tr.DefaultEngine()
memory = engine.createMemory()
executable = engine.compile(prog)

print "x"
print x.value

a.value = 2
b.value = 7
executable.run(memory)

print x.value
