#!/usr/bin/env python

import time
import tractor as tr
import tractor.types_double as tt
import math

q = tt.Quaternion(0,0,0,1)

def f():
    tt.variable(q)
    #tt.goal(tr.mul(q, tt.Vector3(0,0,1)) - tt.Vector3(0,1,0))
    tt.goal(q * tt.Vector3(0,0,1) - tt.Vector3(0,1,0))

prog = tr.record(f)

print prog.constants
print prog.inputs
print prog.instructions
print prog.outputs

solver = tt.LeastSquaresSolver(tr.DefaultEngine())

solver.compile(prog)

solver.tolerance = 1e-12
solver.regularization = 0.01

print q

solver.solve()

print q
print q * tt.Vector3(0,0,1)
