#!/usr/bin/env python

import time
import tractor as tr
import tractor.types_double as tt

print dir(tr)
print dir(tt)

print tt.Scalar()
print tt.Scalar(1.0)

print tt.Scalar().value
print tt.Scalar(5).value

print "a"
print tr.tanh(tt.Scalar(0.3))
print tr.tanh(tt.Scalar(1.0))
print tr.sin(tt.Scalar(5.0))

v = tt.Vector3(3, 4, 5)
print v
tr.vec3_pack(tt.Scalar(1), tt.Scalar(2), tt.Scalar(3), v)
print v
print tt.Vector3(tt.Scalar(1), tt.Scalar(5), tt.Scalar(3))
print tt.Vector3(1,2,3) + tt.Vector3(2,3,4)

print tt.Scalar(10)

# a = tt.Scalar(3)
# print a.value
# a.value = 10
# print a.value
#
# print tr.test()
# print type(tt.Scalar(5))
#
# print tr.test2(5)
# print tr.test2(tt.Scalar(5))
# print tr.test2(tt.Scalar(5).value)
#
# print tr.test3(5)
# print tr.test3(tt.Scalar(5))
# print tr.test3(tt.Scalar(5).value)
