#!/usr/bin/env python

import time
import tractor as tr
import tractor.types_double as tt
import math

b = tt.Scalar(2)

def f():
    global a
    a = tt.Scalar(3)
    tr.input(a)
    tr.input(b)
    #tr.goal(tr.mul(a, 0.01))
    #print " - add", tr.add(a, 0.1)
    #print " - +", a + 0.1
    #tr.goal(tr.add(a, 0.1) * tt.Scalar(0.01))
    tr.goal(a * tt.Scalar(0.01) + 0.01)
    tr.goal(b * tt.Scalar(0.01))
    tr.goal(tr.tanh(a) + tr.tanh(b) - tt.Scalar(0.1))

prog = tr.record(f)

print prog.constants
print prog.inputs
print prog.instructions
print prog.outputs

solver = tt.LeastSquaresSolver(tr.DefaultEngine())
#solver = tt.GradientDescentSolver(tr.DefaultEngine())

solver.compile(prog)

#solver.timeout = 1
solver.tolerance = 1e-12
solver.regularization = 0.01

print a.value, b.value

solver.solve()

print a.value, b.value, math.tanh(a.value) + math.tanh(b.value) - 0.1

# for i in range(100):
#     print a.value, b.value, math.tanh(a.value) + math.tanh(b.value) + 1
#     solver.parameterize()
#     solver.gather()
#     solver.step()
#     solver.scatter()
