#!/usr/bin/env python

import time
import tractor as tr
import tractor.types_double as tt
import math

print tr.__dict__.keys()

b = tt.Vector3(1,2,3)

def f():
    global a
    a = tt.Vector3(2,3,4)
    tr.variable(a)
    tr.variable(b)
    tr.goal(a * tt.Scalar(0.1))
    tr.goal(b * tt.Scalar(0.1))
    tr.goal(a - tt.Vector3(0.1))

prog = tr.record(f)

print prog

solver = tt.LeastSquaresSolver(tr.DefaultEngine())
#solver = tt.GradientDescentSolver(tr.DefaultEngine())

solver.compile(prog)
#solver.timeout = 1
solver.tolerance = 1e-12
solver.regularization = 0.01

print a, b

solver.solve()

print a, b
