#!/usr/bin/env python

import time
import tractor as tr
import tractor.types_double as tt
import math
import copy

inputs = tt.Tensor([1,2,3])
weights = tt.Tensor([[1,2],[2,3],[3,4]])

print "inputs", inputs.shape, inputs.value
print "weights", weights.value
print "outputs", tr.dense_mul_vec_mat(inputs, weights).value

def f():
    print ""
    print "f()"
    x = tt.Tensor([1,2,3])
    print x.shape
    tr.variable(weights)
    tr.goal(tr.dense_mul_vec_mat(x, weights) - tt.Tensor([1,5]))
    print ""

prog = tr.record(f)

print prog

solver = tt.LeastSquaresSolver(tr.DefaultEngine())
solver.compile(prog)
solver.tolerance = 1e-9
solver.regularization = 0.01

print "inputs", inputs.value
print "weights", weights.value
print "outputs", tr.dense_mul_vec_mat(inputs, weights).value

solver.solve()

print "inputs", inputs.value
print "weights", weights.value
print "outputs", tr.dense_mul_vec_mat(inputs, weights).value
