#!/usr/bin/env python

import time
import tractor as tr
import tractor.types_double as tt
import math
import copy

ta = tt.Tensor([[1,2],[3,123]])

def f():
    global tx
    tr.input(ta)
    tb = tt.Tensor([[1,2],[3,99]])
    tx = tr.add(ta, tb)
    tr.goal(tx)

prog = tr.record(f)

print prog.constants
print prog.inputs
print prog.instructions
print prog.outputs

engine = tr.DefaultEngine()
memory = engine.createMemory()
executable = engine.compile(prog)
print ""

print "ta.value", ta.value
print "tx.value", tx.value
print ""

ta.value = [[4,5],[6,7]]
executable.run(memory)
print "tx.value", tx.value
print ""

ta.value = [[1,2],[3,4]]
executable.run(memory)
print "tx.value", tx.value
print ""

solver = tt.LeastSquaresSolver(tr.DefaultEngine())
solver.compile(prog)
solver.tolerance = 1e-9
solver.regularization = 0.01
print ta.value
solver.solve()
print ta.value
