#!/usr/bin/env python

import time
import tractor as tr
import tractor.types_double as tt
import math
import copy

tr.logger.verbosity = 2

inputs = tt.Tensor([[1,2,3],[2,4,6],[3,6,9]])
weights = tt.Tensor([[1,2],[2,3],[3,4]])

print "inputs", inputs.value
print "weights", weights.value
print "outputs", tr.neural_dense(inputs, weights).value

def f():
    #tr.parameter(inputs)
    x = tt.Tensor([[1,2,3],[2,4,6],[3,6,9]])
    tr.variable(weights)
    tr.goal(tr.neural_dense(x, weights) - tt.Tensor([[1,2],[2,4],[3,6]]))

prog = tr.record(f)

print prog

solver = tt.LeastSquaresSolver(tr.DefaultEngine())
solver.compile(prog)
solver.timeout = 1
solver.regularization = 0.00001

print "inputs", inputs.value
print "weights", weights.value
print "outputs", tr.neural_dense(inputs, weights).value

solver.solve()

print "inputs", inputs.value
print "weights", weights.value
print "outputs", tr.neural_dense(inputs, weights).value
