#!/usr/bin/env python

import time
import tractor as tr
import tractor.types_double as tt
import rospy
import sys
import sklearn
import sklearn.cluster

tr.logger.verbosity = 10
tr.init_ros("test")

if len(sys.argv) < 2:
    print ""
    print "usage: collide <robot description>"
    exit(-1)

robot_description = sys.argv[1]
robot_model = tt.RobotModel(robot_description)

#collision_robot = tt.CollisionRobot(robot_model)
#c_link_a = collision_robot.link(name_a)
#c_link_b = collision_robot.link(name_b)

object_goal_position = tt.Vector3()

joint_states = tt.JointStates(robot_model)

def f():
    tr.parameter(object_goal_position)
    for i in range(robot_model.joint_count):
        joint_model = robot_model.joint_model(i)
        joint_state = joint_states.joint_state(i)
        # if isinstance(joint_model, tt.ScalarJointModelBase):
        #     tr.variable(joint_state.position)
        #     tr.goal(joint_state.position)
        if isinstance(joint_model, tt.FloatingJointModel):
            tr.variable(joint_state.pose)
    link_states = robot_model.forward_kinematics(joint_states)
    tr.goal(tr.pose_translation(link_states.link_pose("object")) - object_goal_position)
    #tr.goal(tr.pose_orientation(link_states.link_pose("object")))

#f()

prog = tr.record(f)

diffs = tr.derive(prog)

print ""
print "prog"
print prog
print ""
print "prepare"
print diffs.prepare
print ""
print "forward"
print diffs.forward
print ""
print "reverse"
print diffs.reverse
print ""
print "accumulate"
print diffs.accumulate
print ""

#exit(0)

# solver = tt.GradientDescentSolver(tr.DefaultEngine())
# solver.compile(prog)

solver = tt.LeastSquaresSolver(tr.DefaultEngine())
solver.compile(prog)
#solver.linear_tolerance = 1e-12
solver.tolerance = 1e-6
solver.adaptive_regularization = False
#solver.max_iterations = 3;
solver.timeout = 1
#solver.max_linear_iterations = 1
solver.regularization = 0.0
solver.line_search = False
solver.step_scaling = 1

while True:

    tr.interact("world", "object", object_goal_position, 0.12)

    # solver.solve()


    solver.gather()
    solver.parameterize()
    for i in range(10):
        #solver.parameterize()
        solver.step()
    solver.scatter()

    tr.visualize("/display_robot_state", joint_states)

    time.sleep(0.1)
