#!/usr/bin/env python

import time
import tractor as tr
import tractor.types_double as tt
import rospy
import sys
import sklearn
import sklearn.cluster

#tr.logger.verbosity = 10
tr.init_ros("test")

if len(sys.argv) < 2:
    print ""
    print "usage: collide <robot description>"
    exit(-1)

robot_description = sys.argv[1]
robot_model = tt.RobotModel(robot_description)

collision_robot = tt.CollisionRobot(robot_model)
#c_link_a = collision_robot.link(name_a)
#c_link_b = collision_robot.link(name_b)

object_goal_pose = tt.Pose()

joint_states = tt.JointStates(robot_model)

def f():
    tr.parameter(object_goal_pose)
    for i in range(robot_model.joint_count):
        joint_model = robot_model.joint_model(i)
        joint_state = joint_states.joint_state(i)
        # if isinstance(joint_model, tt.ScalarJointModelBase):
        #     tr.variable(joint_state.position)
        #     tr.goal(joint_state.position)
        if isinstance(joint_model, tt.FloatingJointModel):
            tr.variable(joint_state.pose)
    link_states = robot_model.forward_kinematics(joint_states)
    #tr.goal(tr.pose_residual(link_states.link_pose("object"), object_goal_pose))
    #tr.goal(tr.pose_residual(object_goal_pose, link_states.link_pose("object")))
    tr.goal(tr.pose_translation(link_states.link_pose("object")) - tr.pose_translation(object_goal_pose))
    #tr.goal(tr.quat_residual(tr.quat_inverse(tr.pose_orientation(object_goal_pose)) * tr.pose_orientation(link_states.link_pose("object"))) * tt.Scalar(0.1))
    tr.goal(tr.quat_residual(tr.quat_inverse(tr.pose_orientation(link_states.link_pose("object"))) * tr.pose_orientation(object_goal_pose)) * tt.Scalar(0.1))
    #tr.goal(tr.pose_orientation(link_states.link_pose("object")))
    #tr.goal(tr.pose_orientation(link_states.link_pose("object")))
    collision = tr.collide(
        link_states.link_pose("object"), collision_robot.link("object"),
        link_states.link_pose("world"), collision_robot.link("world")
        )
    tr.goal(tr.relu(tt.Scalar(10) * tr.dot(collision.point_b - collision.point_a, collision.normal)))

    #tr.visualize_points("normals", )

prog = tr.record(f)

diffs = tr.derive(prog)

print ""
print "prog"
print prog
print ""
print "prepare"
print diffs.prepare
print ""
print "forward"
print diffs.forward
print ""
print "reverse"
print diffs.reverse
print ""
print "accumulate"
print diffs.accumulate
print ""

#exit(0)

# solver = tt.GradientDescentSolver(tr.DefaultEngine())
# solver.compile(prog)

solver = tt.LeastSquaresSolver(tr.DefaultEngine())
solver.compile(prog)
#solver.linear_tolerance = 1e-12
solver.tolerance = 1e-12
solver.adaptive_regularization = False
#solver.max_iterations = 3;
solver.timeout = 0.1
solver.max_linear_iterations = 20
solver.regularization = 0.01
solver.line_search = False
solver.step_scaling = 1

while True:

    tr.interact("world", "object", object_goal_pose, 0.2)

    #solver.solve()


    solver.gather()
    solver.parameterize()
    for i in range(1):
        #solver.parameterize()
        solver.step()
    solver.scatter()

    tr.visualize("/display_robot_state", joint_states)

    f()

    time.sleep(0.1)
