#!/usr/bin/env python

import time
import tractor as tr
import tractor.types_double as tt
import rospy
import sys
import sklearn
import sklearn.cluster

tr.logger.verbosity = 10
tr.init_ros("test")

if len(sys.argv) < 2:
    print ""
    print "usage: collide <robot description>"
    exit(-1)

robot_description = sys.argv[1]
robot_model = tt.RobotModel(robot_description)

collision_robot = tt.CollisionRobot(robot_model)

goal_pose = tt.Pose()

samples = collision_robot.link("object").shapes[0].sample(500)
samples = sklearn.cluster.KMeans(n_clusters=50).fit(samples).cluster_centers_

while True:

    tr.interact("world", "object", goal_pose, 0.1)

    joint_states = tt.JointStates(robot_model)
    joint_states.joint_state("object_joint").pose = goal_pose

    link_states = robot_model.forward_kinematics(joint_states)

    collision = tr.collide(
        link_states.link_pose("object"),
        collision_robot.link("object"),
        link_states.link_pose("world"),
        collision_robot.link("world")
        )
    points = [ ]
    print "link collision", collision.point_a, collision.point_b, collision.normal, collision.distance
    points.append(collision.point_a.value)
    points.append(collision.point_b.value)
    tr.visualize_points("collisions", 0.02, (1,0,0,1), points)
    tr.visualize_lines("collision_lines", 0.005, (0,0,1,1), points)

    object_pose = link_states.link_pose("object")

    points = [ ]
    for shape_b in collision_robot.link("world").shapes:
        surface_point = tr.project(tr.pose_translation(object_pose), shape_b)
        points.append(surface_point.point.value)
        points.append(surface_point.point.value + surface_point.normal.value * 0.1)
    tr.visualize_points("pp", 0.02, (1,0,0,1), points)
    tr.visualize_lines("pl", 0.005, (0,1,0,1), points)

    points = [ ]
    for sample in samples:
        points.append((object_pose * tt.Vector3(sample[0:3])).value)
    tr.visualize_points("s", 0.01, (1,0,1,1), points)

    lines = [ ]
    for sample in samples:
        lines.append((object_pose * tt.Vector3(sample[0:3])).value)
        lines.append((object_pose * (tt.Vector3(sample[0:3] + sample[3:6] * 0.03))).value)
    tr.visualize_lines("sl", 0.005, (1,1,0,1), lines)

    tr.visualize("/display_robot_state", joint_states)

    time.sleep(0.02)
