#!/usr/bin/env python

import time
import tractor as tr
import tractor.types_double as tt
import rospy
import sys

tr.logger.verbosity = 10
tr.init_ros("test")

if len(sys.argv) < 4:
    print ""
    print "usage: collide <robot description> <link_a> <link_b>"
    exit(-1)

robot_description = sys.argv[1]
robot_model = tt.RobotModel(robot_description)

name_a = sys.argv[2]
name_b = sys.argv[3]

collision_robot = tt.CollisionRobot(robot_model)
c_link_a = collision_robot.link(name_a)
c_link_b = collision_robot.link(name_b)

print name_a, c_link_a
print name_b, c_link_b

object_pose = tt.Pose()

while True:

    tr.interact("world", "object", object_pose, 0.1)

    joint_states = tt.JointStates(robot_model)
    joint_states.joint_state("object_joint").pose = object_pose

    link_states = robot_model.forward_kinematics(joint_states)

    pose_a = link_states.link_pose(name_a)
    pose_b = link_states.link_pose(name_b)

    collisions = tr.collide(pose_a, c_link_a, pose_b, c_link_b)
    points = [ ]
    for i in range(len(collisions)):
        c = collisions[i];
        print i, c.point_a, c.point_b, c.normal, c.distance
        points.append(c.point_a.value)
        points.append(c.point_b.value)
    tr.visualize_points("collisions", 0.01, (1,1,0,1), points)

    tr.visualize("/display_robot_state", joint_states)

    time.sleep(0.1)
