#!/usr/bin/env python

import time
import tractor as tr
import tractor.types_double as tt
import rospy
import sys
import tractor.types_double_twist as tg

#tr.logger.verbosity = 10
tr.init_ros("test")

if len(sys.argv) >= 2:
    robot_description = sys.argv[1]
    robot_model = tg.RobotModel(robot_description)
    print "link names:", robot_model.link_names

if len(sys.argv) < 3:
    print ""
    print "usage: ik <robot description> <end effector link name(s)...>"
    print ""
    print "example: ik /robot_description fftip"
    exit(-1)

end_effectors = sys.argv[2:]

joint_states = tg.JointStates(robot_model)

link_states = robot_model.forward_kinematics(joint_states)
goal_positions = [tr.pose_translation(link_states.link_pose(eef)) for eef in end_effectors]

def f():
    for i in range(robot_model.joint_count):
        joint_model = robot_model.joint_model(i)
        joint_state = joint_states.joint_state(i)
        if isinstance(joint_model, tg.ScalarJointModelBase):
            tr.variable(joint_state.position)
            if joint_model.limits:
                tr.goal(tr.relu(joint_model.limits.lower - joint_state.position))
                tr.goal(tr.relu(joint_state.position - joint_model.limits.upper))
        if isinstance(joint_model, tg.FloatingJointModel):
            tr.variable(joint_state.pose)
    link_states = robot_model.forward_kinematics(joint_states)
    for i in range(len(end_effectors)):
        tr.parameter(goal_positions[i])
        tr.goal(goal_positions[i] - tr.pose_translation(link_states.link_pose(end_effectors[i])))

prog = tr.record(f)

solver = tt.LeastSquaresSolver(tr.DefaultEngine())
solver.compile(prog)
#solver.linear_tolerance = 1e-12
solver.tolerance = 1e-7
#solver.adaptive_regularization = True
solver.timeout = 1.0 / 30
solver.regularization = 1
solver.line_search = False
#solver.step_scaling = 1.3

while True:
    for i in range(len(end_effectors)):
        tr.interact("base_frame", end_effectors[i], goal_positions[i], 0.05)
    solver.solve()
    tr.visualize("/display_robot_state", joint_states)
    time.sleep(0.01)
