#!/usr/bin/env python

import time
import tractor as tr
import tractor.types_double as tt
import rospy
import sys

tr.logger.verbosity = 10
tr.init_ros("test")

if len(sys.argv) < 3:
    print ""
    print "usage: ik <robot description> <end effector name(s)...>"
    print ""
    print "example: ik /robot_description fftip"
    print ""
    print "available link names:", robot.link_names
    exit(-1)

robot_description = sys.argv[1]
end_effectors = sys.argv[2:]

robot = tt.RobotModel(robot_description)

joint_positions = [tt.Scalar(0) for i in range(robot.variable_count)]

joint_states = tt.JointStates(robot)
robot.compute_kinematics(state)

goal_positions = [tr.pose_translation(state.links.pose(eef)) for eef in end_effectors]

def f():
    for i in range(robot.variable_count):
        if "hand" not in robot.variable_name(i):
            tr.variable(joint_positions[i])
    joint_states.deserialize(joint_positions)
    robot.compute_kinematics(state)
    for i in range(len(end_effectors)):
        tr.parameter(goal_positions[i])
        tr.goal(goal_positions[i] - tr.pose_translation(state.links.pose(end_effectors[i])))

prog = tr.record(f)

solver = tt.LeastSquaresSolver(tr.DefaultEngine())
solver.compile(prog)
solver.regularization = 0.01

while True:

    for i in range(len(end_effectors)):
        tr.interact("base_frame", end_effectors[i], goal_positions[i], 0.05)

    solver.parameterize()
    solver.gather()
    solver.step()
    solver.scatter()

    state = tt.RobotState(robot)
    state.joints.deserialize(joint_positions)
    robot.compute_kinematics(state)

    tr.visualize("/display_robot_state", robot, state.joints)

    #time.sleep(0.1)
