#!/usr/bin/env python

import time
import tractor as tr
import tractor.types_double as tt
import tractor.types_double_twist as tg
import rospy
import sys
import time

print sys.argv

tr.logger.verbosity = 10
tr.init_ros("test")

v = tg.Vector3(.1,.2,.3)

while True:
    tr.interact("base_frame", "test", v, 0.1)
    time.sleep(0.1)
