#!/usr/bin/env python

import tractor

print "t", dir(tractor)
print ""
print "td", dir(tractor.types_double)
print ""
print "tds", dir(tractor.types_double_scalar)
print ""

print "intersection", set(dir(tractor.types_double)).intersection(set(dir(tractor.types_double_scalar)))
print "intersection", set(dir(tractor)).intersection(set(dir(tractor.types_double_scalar)))
print "intersection", set(dir(tractor)).intersection(set(dir(tractor.types_double)))

#print tractor.add.__doc__

#print summary(tractor)

#print tractor.cross(1, 2)
