#!/usr/bin/env python

import time
import tractor as tr
import tractor.types_double as tt
#import tractor.types_float as tt
import numpy as np
import matplotlib.pyplot as plt
import numpy.random

#tr.logger.verbosity = 2

count = 128
noise = 0.2
stdev = 0.2
activation = "tanh"
units = 64
weight_regularization = 0.1
activity_regularization = 0.01
bias_regularization = 0.1
layers = 8
use_bias = True

xx = tt.Tensor()
yy = tt.Tensor()

frequency = 1

def update():
    xx.value = numpy.random.uniform(-5, +5, count).reshape([count,1])
    yy.value = np.sin(xx.value*frequency) + numpy.random.normal(size=xx.value.shape) * noise
update()

tr.profiler.start(1)

input = tt.InputLayer()
output = input
for i in range(layers):
    output = tt.DenseLayer(
        units,
        activation=activation,
        stdev=stdev,
        weight_regularization=weight_regularization,
        activity_regularization=activity_regularization,
        bias_regularization=bias_regularization,
        use_bias=use_bias,
    )(output)
output = tt.DenseLayer(
        1,
        activation="linear",
        stdev=stdev,
        weight_regularization=weight_regularization,
        activity_regularization=activity_regularization,
        bias_regularization=bias_regularization,
        use_bias=use_bias,
    )(output)

network = tt.NeuralNetwork([input], [output])

print "xx", xx
print "xx v", xx.value.shape
print "yy", yy
print "yy v", yy.value.shape

def f():
    print "f begin"
    tr.parameter(xx)
    tr.parameter(yy)
    pp = network.predict(xx)
    print pp
    tr.goal(pp - yy)
    print "f ready"

print "rec begin"
prog = tr.record(f)
print "rec ready"
print prog

def test():
    plt.cla()
    plt.clf()
    plt.scatter(xx.value, yy.value, marker=".")
    xx.value = np.linspace(-5, +5, count).reshape([count,1])
    plt.plot(xx.value, network.predict(xx).value)
    plt.xlim([-5,5])
    plt.ylim([-1.5,1.5])
    key = plt.waitforbuttonpress(timeout=0.001)
    if key is False:
        global frequency
        frequency = numpy.random.uniform(0.5,2.0)
    if key is True:
        exit(0)

# solver = tt.GradientDescentSolver(tr.DefaultEngine())
# solver.learning_rate = 0.0002
# solver.momentum = 0.9

solver = tt.LeastSquaresSolver(tr.DefaultEngine())
solver.regularization = 1
solver.max_linear_iterations = 10
solver.step_scaling = 1

solver.compile(prog)

solver.timeout = 0.005
while True:
    for i in range(1):
        update()
        solver.gather()
        solver.parameterize()
        solver.step()
        solver.scatter()
    #xx.value = np.linspace(-5, +5, count).reshape([count,1])
    test()
