#!/usr/bin/env python

import time
import tractor as tr
import tractor.types_double as tt
import rospy
import sys
import math

tr.logger.verbosity = 10
tr.init_ros("test")

if len(sys.argv) < 2:
    print ""
    print "usage: physics <robot description>"
    exit(-1)

robot_description = sys.argv[1]
robot_model = tt.RobotModel(robot_description)

collision_robot = tt.CollisionRobot(robot_model)

object_start_pose = tt.Pose()

fps = 50
substeps = 20

while True:

    tr.interact("world", "object", object_start_pose, 0.12)

    joint_states = tt.JointStates(robot_model)

    #p = object_start_pose * tr.angle_axis_pose(tt.Scalar(math.pi), tt.Vector3(0,1,0))
    p = object_start_pose

    object_body = tt.RigidBody(p, robot_model.joint_model("object_joint").inertia)
    print "pose", object_body.pose
    print "center", object_body.inertia.center
    print "mass",  object_body.inertia.mass
    print "moment", object_body.inertia.moment

    for k in range(fps*1):

        joint_states.joint_state("object_joint").pose = object_body.pose
        tr.visualize("/display_robot_state", joint_states)
        time.sleep(1.0/fps)

        for j in range(substeps):

            c = tr.collide(
                object_body.pose,
                collision_robot.link("object"),
                tt.Pose.identity,
                collision_robot.link("world")
            )

            for shape in collision_robot.link("object").shapes:
                for vertex in shape.vertices:
                    v = object_body.pose * tt.Vector3(vertex)
                    d = tr.dot(v - c.point_b, c.normal)
                    if d.value < 0:
                        object_body.apply_force(v, c.normal * d * tt.Scalar(-5))

            object_body.apply_damping(tt.Scalar(5), tt.Scalar(5))

            object_body.apply_acceleration(tt.Vector3(0, 0, -9.81))

            object_body.integrate(1.0/substeps/fps)

        points = [ ]
        points.append(c.point_a.value)
        points.append(c.point_b.value)
        tr.visualize_points("collisions", 0.01, (1,1,0,1), points)
