#!/usr/bin/env python

import time
import tractor as tr
import rospy
import std_msgs.msg
import io

tr.init_ros("test")

while True:
    tr.publish("/hello_topic", std_msgs.msg.String(data="hello world"))
    time.sleep(1)
