#!/usr/bin/env python

import time
import tractor as tr
import tractor.types_double as tt
import tractor.types_double_twist as tg
import math

q = tg.Orientation(0,0,0,1)

def f():
    tr.variable(q)
    tr.goal(q * tg.Vector3(0,0,1) - tg.Vector3(0,1,0))

prog = tr.record(f)
print prog

solver = tt.LeastSquaresSolver(tr.DefaultEngine())
solver.compile(prog)
solver.tolerance = 1e-12
solver.regularization = 0.01

print q

solver.solve()

print q
print q * tg.Vector3(0,0,1)
