#!/usr/bin/env python

import time
import tractor as tr
import tractor.types_double as tt
import sys
import gc

tr.logger.verbosity = 10

tr.init_ros("test")

robot_description = "/robot_description"
if len(sys.argv) >= 2:
    robot_description = sys.argv[1]

robot = tt.RobotModel(robot_description)
print("link names:", robot.link_names)

state = tt.RobotState(robot)

joint_states = state.joint_states

state = False
robot = False
gc.collect()

print("sleep")
time.sleep(1)

print(joint_states.serialize())

print("sleep")
time.sleep(1)

print("exit")
