#!/usr/bin/env python

import time
import tractor as tr
import tractor.types_double as tt
import math
import numpy as np
import random

for i in range(100):
    # axis = np.random.normal(0.0, 10.0, size=3)
    # angle = random.uniform(-10, 10)
    xyzw = np.random.normal(0.0, 10.0, size=4)

    quat1 = tt.Orientation(xyzw)
    vec1 = tr.residual(quat1)

    quat2 = tt.Orientation.angle_axis(tr.norm(vec1), tr.normalized(vec1))
    vec2 = tr.residual(quat2)

    print i, quat1, quat2, vec1, vec2

    assert(np.allclose(vec1.value, vec2.value))
    assert(np.allclose(quat1.value, quat2.value) or np.allclose(quat1.value, -quat2.value))

    quat2 = tt.Orientation() + vec1
    vec2 = tr.residual(quat2)

    print i, quat1, quat2, vec1, vec2

    assert(np.allclose(vec1.value, vec2.value))
    assert(np.allclose(quat1.value, quat2.value) or np.allclose(quat1.value, -quat2.value))

print ""

print tr.residual(tt.Orientation(0,0,0,1))
print tr.residual(tt.Orientation(1,0,0,0))
print tr.residual(tt.Orientation(math.sqrt(0.5),0,0,math.sqrt(0.5)))
print tr.residual(tt.Orientation(-math.sqrt(0.5),0,0,-math.sqrt(0.5)))

print ""

print tt.Orientation.angle_axis(tt.Scalar(0), tt.Vector3(1,0,0))
print tt.Orientation.angle_axis(tt.Scalar(math.pi), tt.Vector3(1,0,0))
print tt.Orientation.angle_axis(tt.Scalar(math.pi*2), tt.Vector3(1,0,0))
print tt.Orientation.angle_axis(tt.Scalar(math.pi*2.5), tt.Vector3(1,0,0))
print tt.Orientation.angle_axis(tt.Scalar(math.pi*3), tt.Vector3(1,0,0))

print ""

print tr.residual(tt.Orientation.angle_axis(tt.Scalar(0), tt.Vector3(1,0,0)))
print tr.residual(tt.Orientation.angle_axis(tt.Scalar(math.pi), tt.Vector3(1,0,0)))
print tr.residual(tt.Orientation.angle_axis(tt.Scalar(math.pi*2), tt.Vector3(1,0,0)))
print tr.residual(tt.Orientation.angle_axis(tt.Scalar(math.pi*2.5), tt.Vector3(1,0,0)))
print tr.residual(tt.Orientation.angle_axis(tt.Scalar(math.pi*3), tt.Vector3(1,0,0)))
