#!/usr/bin/env python

import time
import tractor as tr
import tractor.types_double as tt
import rospy
import sys

print sys.argv

tr.logger.verbosity = 10
tr.init_ros("test")

robot = tt.RobotModel("/dexopt_robot_description")

joint_positions = [tt.Scalar(0) for i in range(robot.variable_count)]

def f():
    for pos in joint_positions:
        tr.variable(pos)
    state = tt.RobotState(robot)
    state.joints.deserialize(joint_positions)
    robot.compute_kinematics(state)
    tr.goal(tt.Vector3(0,0,1) - tr.pose_translation(state.links.pose("palm")))

prog = tr.record(f)

solver = tt.LeastSquaresSolver(tr.DefaultEngine())
solver.compile(prog)
solver.tolerance = 0.0001

for i in range(10):
    solver.parameterize()
    solver.gather()
    solver.step()
    solver.scatter()

    state = tt.RobotState(robot)
    state.joints.deserialize(joint_positions)
    robot.compute_kinematics(state)
    print tt.Vector3(0,0,1) - tr.pose_translation(state.links.pose("palm"))
