#!/usr/bin/env python

import sys
import time
import tractor as tr
import tractor.types_double as tt

tr.init_ros("robot_test")

def link(link, indent):
    print " "*indent, "link", link.name, link.inertia.mass
    for j in link.child_joints:
        joint(j, indent + 1)

def joint(joint, indent = 0):
    print " "*indent, "joint", joint.name, joint
    print " "*indent, " origin", joint.origin
    link(joint.child_link, indent + 1)

robot_model = tt.RobotModel(sys.argv[1])
joint(robot_model.root_joint)

active_joints = [joint.name for joint in robot_model.joints if type(joint) != tt.FixedJointModel]
print "active_joints", active_joints
print "joint count", len(active_joints)
