#!/usr/bin/env python

import time
import tractor as tr
import tractor.types_double as tt
import math
import copy
import numpy as np

print tr.neural_bias(tt.Tensor([1,2,3]), tt.Tensor([.1,.2,.3])).value
print tr.neural_bias(tt.Tensor([[1,2,3],[2,3,4]]), tt.Tensor([.1,.2,.3])).value
#exit(0)

inputs = tt.Tensor([1,2,3])
weights = tt.Tensor([[1,2],[2,3],[3,4]])

print "inputs", inputs.value
print "weights", weights.value

print "tr matmul", tr.matmul(inputs, weights).value
print "np matmul", np.matmul(inputs.value, weights.value)

inputs2 = tt.Tensor([[1,2,3],[1,2,3]])
print "tr matmul 2", tr.matmul(inputs2, weights).value
print "np matmul 2", np.matmul(inputs2.value, weights.value)

def f():
    #tr.parameter(inputs)
    x = tt.Tensor(inputs.value)
    tr.variable(weights)
    tr.goal(tr.matmul(x, weights) - tt.Tensor([1,5]))

prog = tr.record(f)

print prog

solver = tt.LeastSquaresSolver(tr.DefaultEngine())
solver.compile(prog)
solver.tolerance = 1e-9
solver.regularization = 0.01

print "inputs", inputs.value
print "weights", weights.value
print "outputs", tr.matmul(inputs, weights).value

#solver.parameterize()
solver.solve()

print "inputs", inputs.value
print "weights", weights.value
print "outputs", tr.matmul(inputs, weights).value
