#!/usr/bin/env python

import time
import math
import numpy as np
import importlib
import tractor as t
import tractor
import inspect
import tractor.types_double as tt
import src.tests

engine = tractor.DefaultEngine()

class Variant:

    def __init__(self, function, module):
        self.program = tractor.record(lambda: function(module))
        # print self.program
        try:
            self.derivatives = tractor.derive(self.program)
        except Exception as ex:
            print self.program
            print ex
            raise
        self.x_compute = engine.compile(self.program)
        self.x_prepare = engine.compile(self.derivatives.prepare)
        self.x_forward = engine.compile(self.derivatives.forward)
        self.x_reverse = engine.compile(self.derivatives.reverse)
        self.scalar_size = 8
        self.memory_forward = engine.createMemory()
        self.memory_reverse = engine.createMemory()

    def make_compute_input(self):
        return np.random.normal(size=self.x_compute.input_buffer_size/self.scalar_size) * 1

    def make_forward_input(self):
        return np.random.normal(size=self.x_forward.input_buffer_size/self.scalar_size) * 1

    def make_reverse_input(self):
        return np.random.normal(size=self.x_reverse.input_buffer_size/self.scalar_size) * 1

    def run_compute_m(self, input, memory):
        self.x_compute.input(input, memory)
        self.x_compute.execute(memory)
        self.x_prepare.execute(memory)
        return np.frombuffer(self.x_compute.output(memory), dtype=np.double)

    def run_compute(self, input):
        self.run_compute_m(input, self.memory_forward)
        return self.run_compute_m(input, self.memory_reverse)

    def run_forward(self, input):
        self.x_forward.input(input, self.memory_forward)
        self.x_forward.execute(self.memory_forward)
        return np.frombuffer(self.x_forward.output(self.memory_forward), dtype=np.double)

    def run_reverse(self, input):
        self.x_reverse.input(input, self.memory_reverse)
        self.x_reverse.execute(self.memory_reverse)
        return np.frombuffer(self.x_reverse.output(self.memory_reverse), dtype=np.double)

    def run(self, compute_input, forward_input, reverse_input):
        ret_compute = self.run_compute(compute_input)
        ret_forward = self.run_forward(forward_input)
        ret_reverse = self.run_reverse(reverse_input)
        return [
            ret_compute,
            ret_forward,
            ret_reverse,
            ]

class GradientTester:

    def __init__(self, modules):
        self.modules = modules
        self.modes = ["compute", "forward", "reverse"]

    def check_output(self, a, b):
        assert(len(a) == len(b))
        ret = [ ]
        for imode in range(len(a)):
            #print np.sqrt(np.mean(np.square(a[imode] - b[imode])))
            ok = np.allclose(a[imode], b[imode])
            #if imode == 0: ok = False
            #print (self.modes[imode].rjust(8)+":"+("\033[92m"+"OK   "+"\033[0m" if ok else "\033[1m"+"\033[91m"+"ERROR"+"\033[0m")),
            #print (self.modes[imode]+":"+("\033[1m"+"\033[92m"+"OK"+"\033[0m" if ok else "\033[1m"+"\033[91m"+"ERROR"+"\033[0m").ljust(20,".")),
            #all_ok = all_ok and ok
            ret.append(ok)
        return np.array(ret, dtype=bool)

    def check_outputs(self, outputs):
        all_ok = True
        for ivar in range(1, len(outputs)):
            all_ok = all_ok and self.check_output(outputs[0], outputs[ivar])
        return all_ok

    def test(self, function):
        print (function.__name__+"").ljust(30, "."),

        variants = [Variant(function, m) for m in self.modules]
        all_ok = np.full(len(self.modes), True, dtype=bool)

        for i in range(100):

            compute_input = variants[0].make_compute_input()
            forward_input = variants[0].make_forward_input()
            reverse_input = variants[0].make_reverse_input()

            if i <= 20: compute_input *= 0.0

            outputs = [v.run(compute_input, forward_input, reverse_input) for v in variants]
            ok = self.check_outputs(outputs)

            if not ok.all():
                for imode in range(3):
                    print ""
                    print " ", self.modes[imode], function.__name__
                    for o in outputs:
                        print "".join(["%.3f".rjust(7) % v for v in o[imode]])
                    print ""

            all_ok = (all_ok & ok)

            if not ok.all():
                break

        for imode in range(len(self.modes)):
            ok = all_ok[imode]
            print (self.modes[imode]+":"+("\033[1m"+"\033[92m"+"OK"+"\033[0m" if ok else "\033[1m"+"\033[91m"+"ERROR"+"\033[0m").ljust(20,".")),
        print ""

        # if not all_ok:
        #     print ""
        #     for imode in range(3):
        #         print " ", self.modes[imode]
        #         for o in outputs:
        #             print "".join(["%.3f".rjust(7) % v for v in o[imode]])
        #         print ""

modules = [
    tractor.types_double,
    tractor.types_double_scalar,
]

tester = GradientTester(modules)
for m in inspect.getmembers(src.tests.Tests(), predicate=inspect.ismethod):
    tester.test(m[1])
