#!/usr/bin/env python

import time
import math
import numpy as np
import importlib
import tractor as t
import tractor
import inspect
import tractor.types_double as tt

#t.logger.verbosity = 1000
t.debug()

class Tests:

    def pose_translation(self, tg):
        pos = tg.Vector3()
        t.variable(pos)
        xyzw = [tt.Scalar(1) for i in range(4)]
        for v in xyzw: t.variable(v)
        #q = tg.Orientation(xyzw)
        q = tg.Orientation([v * tt.Scalar(10) for v in xyzw])
        pose = tg.Pose(pos, q)
        t.goal(t.translation(pose))

    def pose_orientation(self, tg):
        pos = tg.Vector3()
        t.variable(pos)
        xyzw = [tt.Scalar(1) for i in range(4)]
        for v in xyzw: t.variable(v)
        #q = tg.Orientation(xyzw)
        q = tg.Orientation([v * tt.Scalar(10) for v in xyzw])
        pose = tg.Pose(pos, q)
        t.goal(t.residual(t.orientation(pose)))

    def pose_residual(self, tg):
        pos = tg.Vector3()
        t.variable(pos)
        xyzw = [tt.Scalar(1) for i in range(4)]
        for v in xyzw: t.variable(v)
        #q = tg.Orientation(xyzw)
        q = tg.Orientation([v * tt.Scalar(10) for v in xyzw])
        pose = tg.Pose(pos, q)
        t.goal(t.residual(pose))

    def quat_residual(self, tg):

        angle = tt.Scalar()
        t.variable(angle)
        angle *= tt.Scalar(10)

        axis = t.normalized(tg.Vector3(1,6,-3))

        t.goal(t.residual(tg.Orientation.angle_axis(angle, axis)))

    def quat_residual_2(self, tg):

        angle_1 = tt.Scalar()
        t.variable(angle_1)
        axis_1 = t.normalized(tg.Vector3(1,2,3))

        angle_2 = tt.Scalar()
        t.variable(angle_2)
        axis_2 = t.normalized(tg.Vector3(4,-5,6))

        angle_1 *= tt.Scalar(0.2)
        angle_2 *= tt.Scalar(0.2)

        t.goal(t.residual(tg.Orientation.angle_axis(angle_1, axis_1), tg.Orientation.angle_axis(angle_2, axis_2)))

    def quat_residual_3(self, tg):

        angle = tt.Scalar()
        t.variable(angle)

        axis = tg.Vector3()
        t.variable(axis)

        t.goal(t.residual(tg.Orientation.angle_axis(angle, axis)))

    def quat_pack_residual(self, tg):
        xyzw = [tt.Scalar() for i in range(4)]
        for v in xyzw: t.variable(v)
        t.goal(t.residual(tg.Orientation([v * tt.Scalar(10) for v in xyzw])))

    def make_pose(self, tg):
        pos = tg.Vector3()
        t.variable(pos)
        xyzw = [tt.Scalar(1) for i in range(4)]
        for v in xyzw: t.variable(v)
        q = tg.Orientation(xyzw)
        pose = tg.Pose(pos, q)
        w = tg.Vector3()
        t.variable(w)
        t.goal(pose * w)

    def pose_twist_add(self, tg):

        angle = tt.Scalar()
        t.variable(angle)

        axis = tg.Vector3()
        t.variable(axis)

        quat = tg.Orientation.angle_axis(angle, axis)

        pos = tg.Vector3()
        t.variable(pos)

        pose = tg.Pose(pos, quat)

        twist_t = tg.Vector3([1,2,3])
        twist_r = tg.Vector3([2,3,4])
        t.variable(twist_t)
        t.variable(twist_r)

        twist = tg.Twist(twist_t, twist_r) * tt.Scalar(10)

        w = tg.Vector3()
        t.variable(w)

        t.goal(t.inverse(pose + twist + twist) * w)

    def quat_mul(self, tg):

        angle_1 = tt.Scalar()
        t.variable(angle_1)
        axis_1 = t.normalized(tg.Vector3(1,2,3))

        angle_2 = tt.Scalar()
        t.variable(angle_2)
        axis_2 = t.normalized(tg.Vector3(-4,5,6))

        vec = tg.Vector3(2,3,4)
        t.variable(vec)
        t.goal((tg.Orientation.angle_axis(angle_1, axis_1) * tg.Orientation.angle_axis(angle_2, axis_2)) * vec)

    def quat_mul_inv(self, tg):

        angle_1 = tt.Scalar()
        t.variable(angle_1)
        axis_1 = t.normalized(tg.Vector3(1,2,3))

        angle_2 = tt.Scalar()
        t.variable(angle_2)
        axis_2 = t.normalized(tg.Vector3(4,7,-2))

        vec = tg.Vector3(2,3,4)
        t.variable(vec)

        t.goal((t.inverse(tg.Orientation.angle_axis(angle_1, axis_1)) * tg.Orientation.angle_axis(angle_2, axis_2)) * vec)
        t.goal((t.inverse(tg.Orientation.angle_axis(angle_1, axis_1)) * t.inverse(tg.Orientation.angle_axis(angle_2, axis_2))) * vec)
        t.goal((tg.Orientation.angle_axis(angle_1, axis_1) * t.inverse(tg.Orientation.angle_axis(angle_2, axis_2))) * vec)

    def vec_to_quat(self, tg):

        v = tg.Vector3()
        t.variable(v)

        q = tg.Orientation().identity + v * tt.Scalar(10)

        w = tg.Vector3()
        t.variable(w)

        t.goal(q * w)

    def vec_to_quat_1(self, tg):

        angle = tt.Scalar()
        t.variable(angle)

        axis = tg.Vector3()
        t.variable(axis)

        q = tg.Orientation.angle_axis(angle, axis) + tg.Vector3(-1,3,2)
        t.goal(q * tg.Vector3(5,1,3))

    def vec_to_quat_2(self, tg):

        angle = tt.Scalar()
        t.variable(angle)

        axis = tg.Vector3()
        t.variable(axis)

        w = tg.Vector3()
        t.variable(w)

        q = tg.Orientation.angle_axis(angle, axis) + w

        t.goal(q * tg.Vector3(1,2,3))

    def vec_to_quat_3(self, tg):

        angle_1 = tt.Scalar()
        t.variable(angle_1)
        axis_1 = tg.Vector3()
        t.variable(axis_1)

        angle_2 = tt.Scalar()
        t.variable(angle_2)
        axis_2 = tg.Vector3()
        t.variable(axis_2)

        q = tg.Orientation.angle_axis(angle_1, axis_1) * tg.Orientation.angle_axis(angle_2, axis_2) + tg.Vector3(-1,3,2)

        w = tg.Vector3()
        t.variable(w)

        t.goal(q * w)

    def vec_to_quat_inv(self, tg):

        angle = tt.Scalar()
        t.variable(angle)

        axis = tg.Vector3()
        t.variable(axis)

        w = tg.Vector3()
        t.variable(w)

        q = t.inverse(tg.Orientation.angle_axis(angle, axis)) + w

        t.goal(t.inverse(q) * tg.Vector3(1,2,3))

    def twist_translation(self, tg):
        v = tg.Vector3()
        t.variable(v)
        x = tg.Twist(v, tg.Vector3.zero)
        t.goal(x)

    def angle_axis_va_unpack(self, tg):
        a = tt.Scalar(1)
        v = tg.Vector3([1,2,3])
        w = tg.Vector3([2,3,4])
        t.variable(a)
        t.variable(v)
        t.variable(w)
        q = tg.Orientation.angle_axis(a, v)
        q = t.unpack(q)
        for v in q:
            t.goal(v)

    def angle_axis_va(self, tg):
        a = tt.Scalar(1)
        v = tg.Vector3([1,2,3])
        w = tg.Vector3([2,3,4])
        t.variable(a)
        t.variable(v)
        t.variable(w)
        t.goal(tg.Orientation.angle_axis(a, v) * w)

    def angle_axis_va_inv(self, tg):
        a = tt.Scalar(1)
        v = tg.Vector3([1,2,3])
        w = tg.Vector3([2,3,4])
        t.variable(a)
        t.variable(v)
        t.variable(w)
        t.goal(t.inverse(tg.Orientation.angle_axis(a, v)) * w)

    def angle_axis_v(self, tg):
        axis = tg.Vector3()
        t.variable(axis)
        angle = tt.Scalar(1)
        testvector = tg.Vector3(0,1,0)
        t.goal(tg.Orientation.angle_axis(angle, t.normalized(axis)) * testvector - testvector)

    def quat_unpack(self, tg):

        a1 = tt.Scalar()
        t.variable(a1)
        q1 = tg.Orientation.angle_axis(a1, t.normalized(tg.Vector3(1,2,3)))

        a2 = tt.Scalar()
        t.variable(a2)
        q2 = tg.Orientation.angle_axis(a2, t.normalized(tg.Vector3(-4,3,1)))

        xyzw = t.unpack(q1 * q2)
        for v in xyzw:
            t.goal(v)

    def quat_pack(self, tg):

        a1 = tt.Scalar()
        t.variable(a1)
        q1 = tg.Orientation.angle_axis(a1, t.normalized(tg.Vector3(1,2,3)))

        a2 = tt.Scalar()
        t.variable(a2)
        q2 = tg.Orientation.angle_axis(a2, t.normalized(tg.Vector3(-4,3,1)))

        xyzw = t.unpack(q1 * q2)

        w = tg.Vector3()
        t.variable(w)

        t.goal(tg.Orientation(xyzw) * w);

    def quat_pack_2(self, tg):
        xyzw = [tt.Scalar() for i in range(4)]
        for v in xyzw: t.variable(v)
        w = tg.Vector3()
        t.variable(w)
        t.goal(tg.Orientation(xyzw) * w)

    def angle_axis_a(self, tg):
        a = tt.Scalar()
        w = tg.Vector3()
        t.variable(a)
        t.variable(w)
        v = t.normalized(tg.Vector3(1,2,3))
        t.goal(tg.Orientation.angle_axis(a, v) * w)

    def angle_axis_pose_a(self, tg):
        a = tt.Scalar()
        w = tg.Vector3()
        t.variable(a)
        t.variable(w)
        v = t.normalized(tg.Vector3(1,2,3))
        t.goal(tg.Pose.angle_axis(a, v) * w)

    def angle_axis_pose_va(self, tg):
        a = tt.Scalar()
        v = tg.Vector3()
        w = tg.Vector3()
        t.variable(a)
        t.variable(v)
        t.variable(w)
        t.goal(tg.Pose.angle_axis(a, v) * w)

    def angle_axis_pose_p(self, tg):

        a = tt.Scalar()
        v = tg.Vector3()
        t.variable(a)
        t.variable(v)
        pa = tg.Pose.angle_axis(a, v)

        a = tt.Scalar()
        v = tg.Vector3()
        t.variable(a)
        t.variable(v)
        pb = tg.Pose.angle_axis(pa, a, v)

        a = tt.Scalar()
        v = tg.Vector3()
        t.variable(a)
        t.variable(v)
        pc = tg.Pose.angle_axis(pb, a, v)

        a = tt.Scalar()
        v = tg.Vector3()
        t.variable(a)
        t.variable(v)
        pd = t.inverse(tg.Pose.angle_axis(a, v)) * pa

        w = tg.Vector3()
        t.variable(w)

        t.goal(pd * w)

    def angle_axis_pose_inverse(self, tg):

        a = tt.Scalar()
        v = tg.Vector3()
        t.variable(a)
        t.variable(v)
        p = t.inverse(tg.Pose.angle_axis(a * tt.Scalar(10), v))

        w = tg.Vector3()
        t.variable(w)

        t.goal(p * w)

    def vec3_unpack(self, tg):
        a = tg.Vector3()
        t.variable(a)
        data = t.unpack(a)
        for d in data:
            t.goal(d)

    def vec3_pack(self, tg):
        a = tt.Scalar()
        b = tt.Scalar()
        c = tt.Scalar()
        t.variable(a)
        t.variable(b)
        t.variable(c)
        t.goal(tg.Vector3(a, b, c))

    def vec3_cross(self, tg):
        a = tg.Vector3()
        b = tg.Vector3()
        t.variable(a)
        t.variable(b)
        t.goal(t.cross(a, b))

    def vec3_norms(self, tg):
       a = tg.Vector3()
       t.variable(a)
       t.goal(t.norm(a))
       t.goal(t.squaredNorm(a))
       t.goal(t.normalized(a))

    def vec3_normalize(self, tg):
       a = tg.Vector3()
       t.variable(a)
       t.goal(t.normalized(a))

    def vec3_dot(self, tg):
        a = tg.Vector3()
        b = tg.Vector3()
        t.variable(a)
        t.variable(b)
        t.goal(t.dot(a, b))

    def mat3(self, tg):
        vec = tg.Vector3()
        mat1 = tg.Matrix3()
        mat2 = tg.Matrix3()
        t.variable(vec)
        t.variable(mat1)
        t.variable(mat2)
        vec = (mat1 + mat2) * -vec
        t.goal(vec)

    def stuff(self, tg):
        vec = tg.Vector3()
        t.variable(vec)
        angle = tt.Scalar()
        t.variable(angle)
        pose = tg.Pose.angle_axis(angle, tg.Vector3(1,2,3) * tt.Scalar(1/math.sqrt(1*1+2*2+3*3)))
        angle = tt.Scalar()
        t.variable(angle)
        pose2 = tg.Pose.angle_axis(angle, tg.Vector3(1,0,0))
        for i in range(3):
            vec = pose * pose2 * t.inverse(pose * pose) * vec + vec
        angle = tt.Scalar()
        t.variable(angle)
        orientation = tg.Orientation.angle_axis(angle, tg.Vector3(1,2,3) * tt.Scalar(1/math.sqrt(1*1+2*2+3*3)))
        for i in range(2):
            vec = orientation * vec + vec
        t.goal(vec)

    def test_sin(self, tg):
        a = tt.Scalar()
        t.variable(a)
        t.goal(t.sin(a))

    # def test_fail(self, tg):
    #     a = tt.Scalar()
    #     b = tt.Scalar()
    #     t.variable(a)
    #     t.variable(b)
    #     t.goal(t.add_random_normal(a, b))

engine = tractor.DefaultEngine()

class Tester:

    def __init__(self, function):
        self.function = function
        self.program = tractor.record(lambda: function(tractor.types_double_twist))
        self.derivatives = tractor.derive(self.program)
        self.x_compute = engine.compile(self.program)
        self.x_prepare = engine.compile(self.derivatives.prepare)
        self.x_forward = engine.compile(self.derivatives.forward)
        self.x_reverse = engine.compile(self.derivatives.reverse)
        self.scalar_size = 8
        self.memory = engine.createMemory()

    def make_compute_input(self):
        return np.random.normal(size=self.x_compute.input_buffer_size/self.scalar_size) * 1

    def make_forward_input(self):
        return np.random.normal(size=self.x_forward.input_buffer_size/self.scalar_size) * 1

    def run_compute_m(self, input, memory):
        self.x_compute.input(input, memory)
        self.x_compute.execute(memory)
        self.x_prepare.execute(memory)
        return np.frombuffer(self.x_compute.output(memory), dtype=np.double)

    def run_compute(self, input):
        self.run_compute_m(input, self.memory)
        return self.run_compute_m(input, self.memory)

    def run_forward(self, input):
        self.x_forward.input(input, self.memory)
        self.x_forward.execute(self.memory)
        return np.frombuffer(self.x_forward.output(self.memory), dtype=np.double)

    def run(self):

        for rep in range(100):

            delta = 1e-5

            value = self.make_compute_input()
            #self.run_compute(value)

            input_gradient = self.make_forward_input()

            #output_gradient = self.run_forward(input_gradient)

            #numeric_gradient = (self.run_compute(value + input_gradient * (delta * 0.5)) - self.run_compute(value - input_gradient * (delta * 0.5))) * (1 / delta)

            input_value_a = value + input_gradient * (delta * 0.5)
            output_value_a = self.run_compute(input_value_a)
            output_gradient_a = self.run_forward(input_gradient)

            input_value_b = value - input_gradient * (delta * 0.5)
            output_value_b = self.run_compute(input_value_b)
            output_gradient_b = self.run_forward(input_gradient)

            numeric_gradient = (output_value_a - output_value_b) * (1.0 / delta)

            output_gradient = (output_gradient_a + output_gradient_b) * 0.5

            ok = np.allclose(output_gradient, numeric_gradient)

            if not ok:
                print ""
                print (self.function.__name__+"").ljust(25, ".") + " " + "\033[1m"+"\033[91m"+"ERROR"+"\033[0m"
                print "iteration        ", rep
                print "current value    ", value
                print "output value a   ", output_value_a
                print "output value b   ", output_value_b
                print "input gradient   ", input_gradient
                print "output gradient a", output_gradient_a
                print "output gradient b", output_gradient_b
                print "numeric gradient ", numeric_gradient
                print ""
                return

        print (self.function.__name__+"").ljust(25, ".") + " " + "\033[1m"+"\033[92m"+"OK"+"\033[0m"

for m in inspect.getmembers(Tests(), predicate=inspect.ismethod):
    #print m[1]
    Tester(m[1]).run()
