#!/usr/bin/env python

import time
import math
import numpy as np
import importlib
import tractor as t
import tractor
import inspect
import tractor.types_double as tt
import src.tests

#t.logger.verbosity = 1000
t.debug()

engine = tractor.DefaultEngine()

class Tester:

    def __init__(self, function):
        self.function = function
        self.program = tractor.record(lambda: function(tractor.types_double))
        self.derivatives = tractor.derive(self.program)
        self.x_compute = engine.compile(self.program)
        self.x_prepare = engine.compile(self.derivatives.prepare)
        self.x_forward = engine.compile(self.derivatives.forward)
        self.x_reverse = engine.compile(self.derivatives.reverse)
        self.scalar_size = 8
        self.memory = engine.createMemory()

    def make_compute_input(self):
        return np.random.normal(size=self.x_compute.input_buffer_size/self.scalar_size) * 1

    def make_forward_input(self):
        return np.random.normal(size=self.x_forward.input_buffer_size/self.scalar_size) * 1

    def run_compute_m(self, input, memory):
        self.x_compute.input(input, memory)
        self.x_compute.execute(memory)
        self.x_prepare.execute(memory)
        return np.frombuffer(self.x_compute.output(memory), dtype=np.double)

    def run_compute(self, input):
        self.run_compute_m(input, self.memory)
        return self.run_compute_m(input, self.memory)

    def run_forward(self, input):
        self.x_forward.input(input, self.memory)
        self.x_forward.execute(self.memory)
        return np.frombuffer(self.x_forward.output(self.memory), dtype=np.double)

    def run(self):

        for rep in range(100):

            delta = 1e-5

            value = self.make_compute_input()

            if rep <= 20: value *= 0.0

            input_gradient = self.make_forward_input()

            # output_value = self.run_compute(value)
            # output_gradient = self.run_forward(input_gradient)
            # numeric_gradient = (self.run_compute(value + input_gradient * (delta * 0.5)) - self.run_compute(value - input_gradient * (delta * 0.5))) * (1 / delta)

            # input_value_a = value + input_gradient * (delta * 0.5)
            # output_value_a = self.run_compute(input_value_a)
            # output_gradient_a = self.run_forward(input_gradient)
            #
            # input_value_b = value - input_gradient * (delta * 0.5)
            # output_value_b = self.run_compute(input_value_b)
            # output_gradient_b = self.run_forward(input_gradient)
            #
            # numeric_gradient = (output_value_a - output_value_b) * (1.0 / delta)
            #
            # output_gradient = (output_gradient_a + output_gradient_b) * 0.5

            # ok = np.allclose(output_gradient, numeric_gradient)

            input_value_0 = value - input_gradient * delta
            input_value_1 = value
            input_value_2 = value + input_gradient * delta

            output_value_0 = self.run_compute(input_value_0)
            output_value_1 = self.run_compute(input_value_1)
            output_gradient = self.run_forward(input_gradient)
            output_value_2 = self.run_compute(input_value_2)

            numeric_gradient_0 = (output_value_1 - output_value_0) * (1.0 / delta)
            numeric_gradient_1 = (output_value_2 - output_value_1) * (1.0 / delta)

            numeric_gradient = (numeric_gradient_1 + numeric_gradient_0) * 0.5

            #okok = (np.abs(output_gradient - numeric_gradient) <= np.abs(numeric_gradient_1 - numeric_gradient_0))
            #ok = okok.all()

            uncertainty = np.max(np.abs(numeric_gradient_1 - numeric_gradient_0))
            #print uncertainty
            ok = np.allclose(output_gradient, numeric_gradient, atol=max(1e-08, uncertainty))

            if not ok:
                print ""
                print (self.function.__name__+"").ljust(30, ".") + " " + "\033[1m"+"\033[91m"+"ERROR"+"\033[0m"
                print "iteration          ", rep
                print "current value      ", value
                print "input_value_0      ", input_value_0
                print "input_value_1      ", input_value_1
                print "input_value_2      ", input_value_2
                print "output_value_0     ", output_value_0
                print "output_value_1     ", output_value_1
                print "numeric_gradient_0 ", numeric_gradient_0
                print "numeric_gradient_1 ", numeric_gradient_1
                print "numeric_gradient   ", numeric_gradient
                print "output_gradient    ", output_gradient
                print ""
                return

        print (self.function.__name__+"").ljust(30, ".") + " " + "\033[1m"+"\033[92m"+"OK"+"\033[0m"

for m in inspect.getmembers(src.tests.Tests(), predicate=inspect.ismethod):
    #print m[1]
    Tester(m[1]).run()
