#!/usr/bin/env python

import time
import math
import numpy as np
import importlib
import tractor as t
import tractor
import inspect
import tractor.types_double as tt
import src.tests

#t.logger.verbosity = 1000
t.debug()

engine = tractor.DefaultEngine()

class Tester:

    def __init__(self, function):
        self.function = function
        self.program = tractor.record(lambda: function(tractor.types_double_twist))
        self.derivatives = tractor.derive(self.program)
        self.x_compute = engine.compile(self.program)
        self.x_prepare = engine.compile(self.derivatives.prepare)
        self.x_forward = engine.compile(self.derivatives.forward)
        self.x_reverse = engine.compile(self.derivatives.reverse)
        self.scalar_size = 8
        self.memory = engine.createMemory()

    def make_compute_input(self):
        return np.random.normal(size=self.x_compute.input_buffer_size/self.scalar_size) * 1

    def make_forward_input(self):
        return np.random.normal(size=self.x_forward.input_buffer_size/self.scalar_size) * 1

    def run_compute_m(self, input, memory):
        self.x_compute.input(input, memory)
        self.x_compute.execute(memory)
        self.x_prepare.execute(memory)
        return np.frombuffer(self.x_compute.output(memory), dtype=np.double)

    def run_compute(self, input):
        self.run_compute_m(input, self.memory)
        return self.run_compute_m(input, self.memory)

    def run_forward(self, input):
        self.x_forward.input(input, self.memory)
        self.x_forward.execute(self.memory)
        return np.frombuffer(self.x_forward.output(self.memory), dtype=np.double)

    def run(self):

        for rep in range(100):

            delta = 1e-5

            value = self.make_compute_input()
            #self.run_compute(value)

            input_gradient = self.make_forward_input()

            #output_gradient = self.run_forward(input_gradient)

            #numeric_gradient = (self.run_compute(value + input_gradient * (delta * 0.5)) - self.run_compute(value - input_gradient * (delta * 0.5))) * (1 / delta)

            input_value_a = value + input_gradient * (delta * 0.5)
            output_value_a = self.run_compute(input_value_a)
            output_gradient_a = self.run_forward(input_gradient)

            input_value_b = value - input_gradient * (delta * 0.5)
            output_value_b = self.run_compute(input_value_b)
            output_gradient_b = self.run_forward(input_gradient)

            numeric_gradient = (output_value_a - output_value_b) * (1.0 / delta)

            output_gradient = (output_gradient_a + output_gradient_b) * 0.5

            ok = np.allclose(output_gradient, numeric_gradient)

            if not ok:
                print ""
                print (self.function.__name__+"").ljust(25, ".") + " " + "\033[1m"+"\033[91m"+"ERROR"+"\033[0m"
                print "iteration        ", rep
                print "current value    ", value
                print "output value a   ", output_value_a
                print "output value b   ", output_value_b
                print "input gradient   ", input_gradient
                print "output gradient a", output_gradient_a
                print "output gradient b", output_gradient_b
                print "numeric gradient ", numeric_gradient
                print ""
                return

        print (self.function.__name__+"").ljust(25, ".") + " " + "\033[1m"+"\033[92m"+"OK"+"\033[0m"

for m in inspect.getmembers(src.tests.Tests(), predicate=inspect.ismethod):
    #print m[1]
    Tester(m[1]).run()
