#!/usr/bin/env python

import time
import tractor as tr
#import tractor.types_double as tt
import tractor.types_float as tt
import math
import copy

print type(tt.Scalar(1))
print tr.add(tt.Scalar(1), tt.Scalar(1)).value
#tr.add("bla")
