#!/usr/bin/env python

import tractor as tr
import tractor.types_double as tt
import tractor.types_double_twist as tg

v = tg.Vector3()
print v
print v.value
print ""
v.value = [1,2,3]
print v
print v.value
print ""
v = tg.Vector3([2,3,4])
print v
print v.value
print ""

v = tg.Orientation()
print v
print v.value
print ""
v.value = [1,2,3,4]
print v
print v.value
print ""
v = tg.Orientation([2,3,4,5])
print v
print v.value
print ""

v = tg.Matrix3()
print v
print v.value
print ""
v.value = [[1,2,3],[2,3,4],[3,4,5]]
print v
print v.value
print ""
v = tg.Matrix3([[2,3,4],[3,4,5],[4,5,6]])
print v
print v.value
print ""
